### PR TITLE
Read/write packets with proc macro

### PR DESCRIPTION
**Pull request by AndreasHGK**
-- begin release notes --
Rewrite zuri_net to use macro for reading/writing packets
-- end release notes --

### CODE REVIEW

**Comment by jrcarl624** [comment]
Wouldn't a serde impl be a better option rather than reinventing the wheel?

**Comment by AndreasHGK** [comment]
> Wouldn't a serde impl be a better option rather than reinventing the wheel?

This is not quite possible due to how some packets are structured. Look at `ClientCacheBlobStatus` for instance, which contains 2 vectors but writes the length of both vectors before the content. I also feel like the current way is just a bit more optimised. We don't need the field names of packets.

**Comment by jrcarl624** [comment]
If you could reference the file, I haven't cloned the project yet as I am out and about currently.

**Comment by AndreasHGK** [comment]
**After macro**
https://github.com/zuri-mc/zuri/blob/e8edfb14cfae9c287be836d6bd8392e4141bb345/zuri_net/src/proto/packet/client_cache_blob_status.rs

**Before macro**
https://github.com/zuri-mc/zuri/blob/49c70cc923ec30a9c97173c60da87ea6731d038a/zuri_net/src/proto/packet/client_cache_blob_status.rs

**Comment by jrcarl624** [comment]
I mean all it would require is an attribute for serde to follow.

**Comment by jrcarl624** [comment]
We could just write a serde implementation later for translating packet structures for readability for documentation.

**Comment by JustTalDevelops** [comment]
I heavily doubt moving to a standardized implementation like Serde will do much good here; the Minecraft protocol, and specifically the Bedrock protocol, is an inconsistent jumble and mess. There is various inconsistencies with how data is written and read and the example Andreas gave is one of many. We **need** flexibility and control over how it's structured, and maybe Serde does offer it, but I doubt it's to the curated extent we would require.

**Review by TwistedAsylumMC — APPROVED** [review]

**Pull request merged**
