### PR TITLE
Set const for byte_f32 reader and writer

### PR DESCRIPTION
**Pull request by jrcarl624**

### CODE REVIEW

**Review by AndreasHGK — CHANGES_REQUESTED** [review]
Maybe this could be one constant `BYTE_F32_FACTOR`, since they are the same value. I don't think having two constants is the way to go here.

**Review by AndreasHGK — APPROVED** [review]
Looks good! Don't forget to run cargo fmt.

**Comment by jrcarl624** [comment]
I mean that's the result of the compilation, it simplifies it. I would see why you would say that.

**Comment by AndreasHGK** [comment]
I feel like its better to just keep the `360.0 / 256.0`, it explicitly shows where the number came from.

**Review by AndreasHGK — CHANGES_REQUESTED** [review]
This can be merged once the requested changes are implemented

**Comment by AndreasHGK** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
